version: '3'
services:
  Telegram_Bot:
    container_name: Telegram_BOT
    image: pawerak/pyrogram-schedule:latest
    restart: unless-stopped
    volumes:
      - ~/path/to/scripts:/usr/scripts
    enviroment:
      - TZ=Europe/Warsaw
